accept_dms_from_not_in_the_channel: false
avatar: static
block_money_transfer: true
blocked_users: {}
blocked_words: {}
chat_key: DIK_RETURN
close_chat: true
current_avatar: pysaic_icon_actor_renegade_17
current_faction: Bandit
death_report_type: OnlineFactions
death_reports: false
disconnect_when_blowout_or_underground: false
faction_setting: GameSynced
in_game_users_display: CRCR
news_duration: 3250
news_sound: true
nick: Researcher_Kinnunen
nick_auto_complete_key: DIK_TAB
password: ''
user_list_display: Names in alphabetical order
