--| CRC configuration
--| By Amon. modified by for PySAIC integration

-- Default keyboard layout indices
local keyboard_layout = 1
local keyboard_layout_cyrillic = 1

keyboard_layouts = {
	{ 1, "usa" },
	{ 2, "uk" },
	{ 3, "albanian" },
	{ 4, "azerbaijani" },
	{ 5, "azerbaijani_2010" },
	{ 6, "czech_qwerty" },
	{ 7, "czech_qwertz" },
	{ 8, "danish" },
	{ 9, "dutch" },
	{10, "estonian" },
	{11, "faroese" },
	{12, "finnish"},
	{13, "french_azerty" },
	{14, "french_bepo" },
	{15, "french_canada" },
	{16, "german" },
	{17, "hungary" },
	{18, "icelandic" },
	{19, "irish" },
	{20, "italian" },
	{21, "latvian" },
	{22, "lithuanian_qwerty"},
	{23, "lithuanian" },
	{24, "maltese_47" },
	{25, "maltese_48" },
	{26, "norwegian" },
	{27, "polish" },
	{28, "portuguese" },
	{29, "brazil" },
	{30, "romanian" },
	{31, "slovak_qwerty" },
	{32, "slovak_qwertz"},
	{33, "sorbian" },
	{34, "spanish" },
	{35, "spanish_latinamerican" },
	{36, "swedish" },
	{37, "swiss_french" },
	{38, "swiss_german" },
	{39, "turkish_f" },
	{30, "turkish_q" },
	{40, "turkmen" },
	{41, "vietnamese" },
}

keyboard_layouts_cyrillic = {
	{1, "russian" },
	{2, "azerbaijani" },
	{3, "bashkir" },
	{4, "belarusian" },
	{5, "bulgarian" },
	{6, "kazakh" },
	{7, "kyrgyz" },
	{8, "macedonian" },
	{9, "mongolian" },
	{10, "serbian" },
	{11, "tajik" },
	{12, "tatar" },
	{13, "ukrainian" },
	{14, "uzbek" },
}

--- MCM Config
local mcm_config = {
	id = "crc", sh = true, gr = {
		{id = "keyboard_layout", type = "list", val = 2, content = keyboard_layouts, def = keyboard_layout},
		{id = "keyboard_layout_cyrillic", type = "list", val = 2, content = keyboard_layouts_cyrillic, def = keyboard_layout_cyrillic},
	}
}

--- returns CRCR Configuration
function get()
    local config = {}

    -- Map pysaic options
	config.chat_key = pysaic_config.option.chatKey
	config.nick_auto_complete_key = pysaic_config.option.nickAutoCompleteKey
	config.news_duration = pysaic_config.option.newsDuration
	config.news_sound = pysaic_config.option.newsSound
	config.close_chat = pysaic_config.option.closeChat
	config.disconnect_on_blowout = pysaic_config.option.disconnectWhenBlowoutOrUnderground
	config.disconnect_when_underground = pysaic_config.option.disconnectWhenBlowoutOrUnderground
	config.max_messages_size = pysaic_config.MAX_MESSAGE_LOG_LENGTH

    -- Add local keyboard settings
    config.keyboard_layout = keyboard_layout
    config.keyboard_layout_cyrillic = keyboard_layout_cyrillic

	return config
end

function on_mcm_load()
    return mcm_config
end

local function load_settings()
	if ui_mcm then
        local val = ui_mcm.get("crc/keyboard_layout")
        if val then keyboard_layout = val end

        val = ui_mcm.get("crc/keyboard_layout_cyrillic")
        if val then keyboard_layout_cyrillic = val end
	end
end

function on_game_start()
	RegisterScriptCallback("on_game_load", load_settings)
	RegisterScriptCallback("on_option_change", load_settings)
end
