--| Adding a new tab to the pda
--| Inspirated by iTheon's PDA Tasbar

NODE_ID = "eptChat"

--- here are all the modifications the mod makes to the game's original functions
function create_overrides()
    local original_set_active_subdialog = pda.set_active_subdialog

    --- @param section string
    pda.set_active_subdialog = function (section)
        if pysaic_state.USE_PDA and section == NODE_ID then
            local our_pda = crc_pda.get_ui()
            if our_pda then
                our_pda:update_ui()
            end
            return our_pda
        else
            return original_set_active_subdialog(section)
        end
    end
end

function on_game_start()
	RegisterScriptCallback("on_game_load", create_overrides)
end