--| PySAIC IO
--| Handles socket communication

local conn = require("pysaic_cm")
local handshake_sent = false

function init()
    conn.init()
end

function send(message, ...)
    conn.send(string.format(message, ...))
end

function send_handshake(body)
    printf("Sending handshake with body: %s", body)
	send("Handshake/%s/%s", pysaic_config.SCRIPT_VERSION, body or "null")
end

function update()
    local data = conn.update()

    local status = conn.status()
    if status == "open" and not handshake_sent then
        send_handshake("reconnect")
        handshake_sent = true
    elseif status == "closed" or status == "error" then
        handshake_sent = false
    end

    if data then
        local messages = {}
        for s in data:gmatch("[^\n]+") do
            messages[#messages+1] = s
        end
        return messages
    end
    return nil
end
