--| PySAIC IO
--| Handles socket communication

local conn = require("pysaic_cm")
local handshake_sent = false

function init()
    conn.init()
end

function send(message, ...)
    conn.send(string.format(message, ...))
end

function send_handshake(body)
    printf("Sending handshake with body: %s", body)
	send("Handshake/%s/%s", pysaic_config.SCRIPT_VERSION, body or "null")
end

function update()
    local data = conn.update()

    local status = conn.status()
    if status == "open" and not handshake_sent then
        send_handshake("reconnect")
        handshake_sent = true
    elseif status == "closed" or status == "error" then
        handshake_sent = false
    end

    if data then
        local messages = {}
        local last_pos = 1
        while true do
            local next_newline = data:find("\n", last_pos)
            if next_newline then
                local message = data:sub(last_pos, next_newline - 1)
                if #message > 0 then
                    messages[#messages + 1] = message
                end
                last_pos = next_newline + 1
            else
                local message = data:sub(last_pos)
                if #message > 0 then
                    messages[#messages + 1] = message
                end
                break
            end
        end
        return messages
    end
    return nil
end
