-- PySAIC's Constants Module

UserDisplayStyleEnum = {
	CRCR = "CRCR",
	PySAIC_Card = "PySAIC_Card",
	PySAIC_Compact = "PySAIC_Compact",
}
userDisplayToNodeMap = {
	[UserDisplayStyleEnum.CRCR] = "user",
	[UserDisplayStyleEnum.PySAIC_Card] = "pysaic_card",
	[UserDisplayStyleEnum.PySAIC_Compact] = "pysaic_compact",
}

IRCUserModeEnum = {
    Normal = "Normal",
    Operator = "op",
    HalfOp = "halfop",
    Voice = "voice",
    Bot = "Bot",
}

InGameDisplayStyleEnum = {
    Name = "Name",
    Faction = "Faction",
    Faction_Counter = "Faction_Counter",
    OnlineStatus = "OnlineStatus",
}

FACTION_COLORS = {
    actor_anonymous = GetARGB(255, 255, 255, 255),
    actor_army = GetARGB(255, 118, 238, 120),
    actor_bandit = GetARGB(255, 205, 104, 57),
    actor_csky = GetARGB(255, 10, 200, 255),
    actor_dolg = GetARGB(255, 255, 48, 48),
    actor_ecolog = GetARGB(255, 255, 140, 0),
    actor_freedom = GetARGB(255, 0, 255, 127),
    actor_greh = GetARGB(255, 139, 10, 10),
    actor_killer = GetARGB(255, 30, 144, 255),
    actor_monolith = GetARGB(255, 154, 50, 205),
    actor_renegade = GetARGB(255, 173, 255, 47),
    actor_stalker = GetARGB(255, 250, 250, 110),
    actor_isg = GetARGB(255, 255, 168, 158),
    actor_zombied = GetARGB(255, 255, 255, 255),
}